[project]
name = "nonebot-plugin-cnrail"
version = "0.1.0"
description = "Template plugin project"
authors = [{ name = "student_2333", email = "lgc2333@126.com" }]
dependencies = [
    "nonebot2>=2.1.2",
    "nonebot-adapter-onebot>=2.2.0",
    "pydantic>=1.10.4,<2",
    "httpx>=0.25.2",
    "nonebot-plugin-send-anything-anywhere>=0.4.0",
]
requires-python = ">=3.8,<4.0"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
homepage = "https://github.com/XieXiLin2/nonebot-plugin-cnrail"

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
